### PR TITLE
ENH: add more customization options

### PR DESCRIPTION
**Pull request by fedorov**
Added LoG kernel size, resampling and wavelet, see #25

Dependent on https://github.com/Radiomics/pyradiomics/pull/280

Not working at the moment - feature calculation is failing - I am missing
something!

### CODE REVIEW

**Comment by fedorov** [comment]
@JoostJM would be great if we could look into this together!

**Comment by pieper** [comment]
@fedorov , @JoostJM told me he will be on vacation for a couple weeks and won't be checking email.  Maybe we should try to do this without him?

**Comment by fedorov** [comment]
I know, I agree - maybe go over the code tomorrow during hangout? I don't have much time left today.

**Comment by fedorov** [comment]
Ok, so I think I figured it out - see PRs above for the master and custom `slicer` branch. I tested, and it works for me.

@pieper if you have time, feel free to review/merge so it gets into tomorrow's extension package, otherwise let's discuss tomorrow at the call. Depends on https://github.com/Radiomics/pyradiomics/issues/281.

**Comment by pieper** [comment]
Yes, let's talk about it tomorrow.  I built this branch and ran the SelfTest with no errors.  

But I did get the error when trying to run from the GUI.

I think we should add traceback stacktrace prints in every except clause to help debug.

```
except:
    import traceback
    traceback.print_exc()
```

**Comment by fedorov** [comment]
Did you test after updating `pyradiomics` `featureextractor.py` in the extension folder to the one in https://github.com/Radiomics/pyradiomics/pull/281?

**Comment by pieper** [comment]
Added https://github.com/Radiomics/SlicerRadiomics/issues/27

**Comment by pieper** [comment]
No but I will check now.

**Comment by pieper** [comment]
Yes, it works now.  I'll go ahead and merge.

Nice fix! 👍

**Comment by fedorov** [comment]
Thanks! 👍

**Pull request merged**
