### PR TITLE
Support standalone packaging

### PR DESCRIPTION
**Pull request by jcfr**
This commit updates the extension build system so that it installs
pyradiomics and its dependencies in its own directory and package it
along side with the SlicerRadiomics scripted module.

### CODE REVIEW

**Comment by jcfr** [comment]
xref https://github.com/Slicer/Slicer/pull/704

**Comment by fedorov** [comment]
Great, thanks!

Should we wait until https://github.com/Slicer/Slicer/pull/704 is merged, before merging this and adding SlicerRadiomics to the ExtensionIndex?

**Comment by jcfr** [comment]
> before merging this and adding SlicerRadiomics to the ExtensionIndex?

Yes. It wouldn't work otherwise. 

It still need to be test on MacOSx and Windows. 

Simply generating a package and using "Install from file" in Slicer should be sufficient to confirm it works.

**Comment by fedorov** [comment]
Ok - I will test on Mac

**Comment by fedorov** [comment]
>> Simply generating a package and using "Install from file" in Slicer should be sufficient to confirm it works.
> Ok - I will test on Mac

Looks like I will still need to compile Slicer from https://github.com/Slicer/Slicer/pull/704 first to be able to do this.

**Comment by fedorov** [comment]
@jcfr it does not work on Mac. pyradiomics import fails. I attach the generated package.

[b13b144-macosx-amd64-SlicerRadiomics-gitc484042-2017-04-20.tar.gz](https://github.com/Radiomics/SlicerRadiomics/files/947733/b13b144-macosx-amd64-SlicerRadiomics-gitc484042-2017-04-20.tar.gz)

**Comment by jcfr** [comment]
Thanks @fedorov , that is very helpful.

I just pushed a commit that should address it. There is no need to rebuild Slicer, only the extension package.

**Comment by fedorov** [comment]
@jcfr I confirm it works for me on mac - thank you!

**Comment by fedorov** [comment]
@jcfr considering Slicer/Slicer#704 is integrated, I will proceed with adding SlicerRadiomics to ExtensionIndex.

**Comment by jcfr** [comment]
This branch can now be integrated.

> I will proceed with adding SlicerRadiomics to ExtensionIndex.

👍

**Comment by fedorov** [comment]
Thank you very much JC!

**Pull request merged**
